apiVersion: apps/v1
kind: Deployment
metadata:
  name: srrs-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srrs-frontend
  template:
    metadata:
      labels:
        app: srrs-frontend
    spec:
      containers:
        - name: srrs-frontend
          image: mbah1234/srrs-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
